### ISSUE TITLE
Reorganize steps

### ISSUE THREAD

**Issue by thomascoumau** [jcalixte/failwell#5]
While coding, I sometimes realize the following steps I wrote are not correct and I want to change them. There is already a button to add tasks but it would be really helpful if we can reorgarnize all the tasks in the order we want and maybe cancel some of them.

It would be awesome, if possible, to have an history of the task before and after the run too to display the divergences before and after the coding was done.

**Comment by jcalixte** [comment]
Adding the fact that for now, for every edits, the timer resets.
